### ISSUE TITLE
Issue when running a command

### ISSUE THREAD

**Issue by TESTACCOUNTLOLXD** [CloneTrooper1019/Roblox_0.3.368.0#12]
when you run a command it gives you an error and you are unable to play the game. 

an example for when you type in "game.Players:CreateLocalPlayer(0)":
 - ScriptContext::executeInNewThread game.Players:CreateLocalPlayer(0)
 - CreateLocalPlayer is not a valid member of Players
 - stack =Script, line 1: (null)
 - stack end
 - DoExecScript failed because CreateLocalPlayer is not a valid member of Players. game.Players:CreateLocalPlayer(0)

**Comment by CloneTrooper1019** [comment]
The correct function in this particular build is `Players:createLocalPlayer(int userId)`

**Comment by TESTACCOUNTLOLXD** [comment]
it tells me :"attempt to index global 'Players' (a nil value)
 - DoExecScript failed because Script:1: attempt to index global 'Players' (a nil value). Players:createLocalPlayer(0)" though

**Comment by CloneTrooper1019** [comment]
`game.Players:createLocalPlayer(0):LoadCharacter()`
