### ISSUE TITLE
Cannot find the code

### ISSUE THREAD

**Issue by TRex-Code** [CloneTrooper1019/Roblox_0.3.368.0#15]
Where is the code located i want to see how ROBLOX programmed their client.

**Comment by CloneTrooper1019** [comment]
We don’t have any code, just the binaries!
The source of this version has never been public.

**Comment by HuntaDevisgay** [comment]
retard.mp4

**Comment by CloudCreations759** [comment]
ok problem is that the code is located in the .exe not in any .txt. if you go to notepad it will just show encrypted code, maybe you can open the .exe through Visual Studio and i dont know, maybe it will show the actual code, or give you an error.

**Comment by HuntaDevisgay** [comment]
The heck you are talking about my dude, a fucking .exe is not a .sln please make sure to check that before fucking posting, thanks.
