### ISSUE TITLE
"An error occurred trying to launch Roblox" or something, is this expected for this build?

### ISSUE THREAD

**Issue by WackyH-OS** [CloneTrooper1019/Roblox_0.3.368.0#19]
When I try and actually play a game (I know the risks I just wanna see the UI for a minute myself) it throws out an error saying that it couldn't launch the player or something. Is there any way to get a game to open within the build?

**Comment by HuntaDevisgay** [comment]
Your problem we told to not use the client for hosting.
Just use your mind

**Comment by WackyH-OS** [comment]
Oh, sorry, forgot.
