### ISSUE TITLE
Issues while trying to load in a place

### ISSUE THREAD

**Issue by FruitersFruities** [CloneTrooper1019/Roblox_0.3.368.0#20]
There is this issue when im trying to load a place, for example, Crossroads.
> game:load("rbxasset://../../extra/places/Crossroads.rbxl")
Tue Mar 16 15:00:07 2021 - ScriptContext::executeInNewThread game:load("rbxasset://../../extra/places/Crossroads.rbxl")
Tue Mar 16 15:00:07 2021 - rbxasset://../../extra/places/Crossroads.rbxl doesn't exist
Tue Mar 16 15:00:07 2021 - rbxasset://../../extra/places/Crossroads.rbxl doesn't exist, getContent failed: rbxasset://../../extra/places/Crossroads.rbxl
Tue Mar 16 15:00:07 2021 - stack =Script, line 1: (null)
Tue Mar 16 15:00:07 2021 - stack end
Tue Mar 16 15:00:07 2021 - DoExecScript failed because rbxasset://../../extra/places/Crossroads.rbxl doesn't exist, getContent failed: rbxasset://../../extra/places/Crossroads.rbxl. game:load("rbxasset://../../extra/places/Crossroads.rbxl")

Is there any solution to this?

**Comment by CloneTrooper1019** [comment]
Did you change how the folders are laid out?

`rbxasset://` points to the `client/content` folder, so `client/content/../../extra/places/Crossroads.rbxl` should be valid. `rbxasset://../../` collapses to the root directory of the repository, or at least it's supposed to.

Do you have the `extra` folder with `Crossroads.rbxl` in it?

**Comment by TuxSeal1** [comment]
If you are trying to launch Crossroads and the extension is an .rbxl, I figured if you copied the script that Clone has put in the description of the code, make a .txt anywhere you can access it, open the .txt and paste the code in there, it should work when you try to load.

**Comment by CloneTrooper1019** [comment]
Alternatively you guys can just use `File -> Open` on the Crossroads file...
Don't know why there'd be any problems loading the lua file otherwise.
