### ISSUE TITLE
Cannot open toolbox

### ISSUE THREAD

**Issue by hithere145235** [CloneTrooper1019/Roblox_0.3.368.0#21]
Im trying to load up crossroads and trying to go to toolbox just shows the newer roblox website and an error

**Comment by FruitersFruities** [comment]
You need an old version of whatever browser you use or smth maybe, the toolbox doesnt work because this is windows 10, 2007 supported a windows xp browser.

**Comment by CloneTrooper1019** [comment]
Yeah, the legacy toolbox is beyond defunct at this point, much like the start page that the Roblox client tries to connect you to when you first open it.  There's no fixing that unless you use a different webhost that emulates it properly.

**Comment by CloudCreations759** [comment]
You will not modify this build don't you, CloneTrooper?
