### ISSUE TITLE
EXE causes Windows Defender to freak out

### ISSUE THREAD

**Issue by thereal123dprinter** [CloneTrooper1019/Roblox_0.3.368.0#30]
I'm trying to install this onto my sister's device, but when unzipping the file windows deletes the EXE and says it's a Trojan. Is there any reason for this to be happening, or any fixes?

**Comment by CloneTrooper1019** [comment]
I've added the following disclaimer explaining the situation:
https://github.com/CloneTrooper1019/Roblox_0.3.368.0#important-antivirus-disclaimer
