### ISSUE TITLE
It says this when i try to open it

### ISSUE THREAD

**Issue by BIGMANONTHEBLOCC** [CloneTrooper1019/Roblox_0.3.368.0#37]
![Screenshot 2021-04-06 171827](https://user-images.githubusercontent.com/82061873/113779749-2dd83080-96fc-11eb-8e36-eab14e8ee529.png)

**Comment by BrentDaMage** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=26347
You need the 2005 VC++ Redistributable.
