### ISSUE TITLE
Add command which instantly runs the game.

### ISSUE THREAD

**Issue by GlowingUmbreon** [CloneTrooper1019/Roblox_0.3.368.0#4]
Currently you need to run 3 commands to get the game running. It would be better to have a command which runs all three e.g. `game:service("RunService"):run() if not game.Players.LocalPlayer then game.Players:createLocalPlayer(0) end game.Players.LocalPlayer:LoadCharacter() `
```lua
game:service("RunService"):run() 
if not game.Players.LocalPlayer then 
    game.Players:createLocalPlayer(0) 
end 
game.Players.LocalPlayer:LoadCharacter() 
```

**Comment by Mantaraix** [comment]
what this is redundant

**Comment by BrentDaMage** [comment]
This isn't really within the realm of possibilities right now. Come back when we can define custom ClassDescriptors on pre-compiled clients, then maybe we can talk. lol

**Comment by pizzaboxer** [comment]
game.Players:createLocalPlayer(0):LoadCharacter() and then just click the green play button at the top lol

**Comment by CloneTrooper1019** [comment]
I’ve technically solved this now with the new code snippets added to README.md, let me know if this isn’t sufficient :)!
