### ISSUE TITLE
Play solo doesn't work

### ISSUE THREAD

**Issue by hahayes420** [CloneTrooper1019/Roblox_0.3.368.0#44]
how to fix this

**Comment by UBUNTUTHEDISTRO** [comment]
Just copy this code and name it (something).lua
game.Players:createLocalPlayer(0)
game.Players.LocalPlayer:LoadCharacter()
game:service("RunService"):run()

To respawn put this in View > Toolbars > Command
game.Players.LocalPlayer:LoadCharacter()
