### ISSUE TITLE
Unable to run Roblox.exe

### ISSUE THREAD

**Issue by WackyH-OS** [CloneTrooper1019/Roblox_0.3.368.0#7]
It says something about side-by-side something. I installed the Visual C++ 2005 pack. I'm confused.

**Comment by Yakov5776** [comment]
side-by-side usually happens when you don't have the VC++ 2005 redist pack, you're sure you installed the correct one? (And make sure you got the x86 one)

**Comment by WackyH-OS** [comment]
Oh, I thought because I had a x64 processor I got the x64 one, is it ok if the two are on the same PC?

**Comment by Yakov5776** [comment]
yes, it goes according to the binaries architecture not your pc, although you won't be able to run x64 binaries/x64 redist on a x86 machine

**Comment by Yakov5776** [comment]
You can close this issue if it's been resolved
