### ISSUE TITLE
Problems opening

### ISSUE THREAD

**Issue by hardwut** [CloneTrooper1019/Roblox_0.3.368.0#9]
When I double click on the app it says something about side-by-side and stuff. I've downloaded the 2005 C++ thing before and it still wont work. Please help.

**Comment by Vulpovile** [comment]
Make sure you installed both the x86 and x64 ones.

**Comment by Mantaraix** [comment]
https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/

**Comment by CloneTrooper1019** [comment]
If you’re still having problems let us know.
